services:
  test-db:
    image: "postgres:15"
    command: "postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0"
    tmpfs: "/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db-test"
      PGDATA: "/var/lib/postgresql/data"
    profiles:
      - "test"
    ports:
      - "54320:5432"
  tests:
    build:
      dockerfile: "./tests.dockerfile"
      context: "."
    env_file:
      - "./env/test.env"
    depends_on:
      - "test-db"
    profiles:
      - "test"
  dev-db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db"
    profiles:
      - dev
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  backend:
    build:
      dockerfile: "./backend.dockerfile"
      context: "."
    env_file:
      - "./env/dev.env"
    ports:
      - "8000:80"
    profiles:
      - dev
      - prod
    depends_on:
    - "dev-db"
volumes:
  postgres-data: null
