services:
  test-db:
    image: "postgres:15"
    command: "postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0"
    tmpfs: "/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db-test"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "54321:5432"
  dev-db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "54320:5432"
volumes:
  postgres-data: null
