services:
  test-db:
    image: "postgres:15.3"
    tmpfs: "/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db-test"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "--lc-collate=C"
    ports:
      - "54321:5432"
    profiles:
      - 'default'
      - dev
  dev-db:
    image: "postgres:15.3"
    command: "postgres -c log_statement=all"
    environment:
      POSTGRES_USER: "devin"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dzelda-db"
      #TODO maybe use a different collation per query based on language, and update tests to match
      #See https://stackoverflow.com/questions/62525260/what-is-the-best-way-to-replicate-postgresql-sorting-results-in-javascript
      #and https://stackoverflow.com/questions/44055727/localecompare-when-testing-strings-sorted-in-en-us-utf8
      POSTGRES_INITDB_ARGS: "--lc-collate=C"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "54320:5432"
    profiles:
      - 'default'
      - dev
  email-server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Web interface for viewing emails
      - "1025:1025"  # SMTP server for receiving emails
    profiles:
      - 'default'
      - dev
  server:
    build:
      dockerfile: backend.dockerfile
      context: .
    env_file:
      - env/prod.env
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    profiles:
      - prod
  nginx-proxy:
    restart: unless-stopped
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - prod
    depends_on:
      - server
    volumes:
      - ./public/:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem


volumes:
  postgres-data: null
  certbot-etc: null
  certbot-var: null
