name: "Deploy Server"
on:
  release:
    types: [ released ]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SERVER_SSH_HOST }}

      - name: Run the deployment script
        run: ssh production './deploy.sh'
